mqtt:
 enabled: false


objects:
 track:
   # - person
   - car
   - motorcycle
   - plate


# cameras:
#   test:
#     ffmpeg:
#       inputs:
#         - path: /media/frigate/camera-test.mp4
#           input_args: -re -stream_loop -1 -fflags +genpts
#           roles:
#             - detect
#             - rtmp
#     detect:
#       height: 1080
#       width: 1920
#       fps: 5
#   camera1:
#     ffmpeg:
#       hwaccel_args: preset-nvidia-h264
#       inputs:
#         - path: rtsp://admin:0938447416hd@222.253.40.180:1024/Streaming/Unicast/channels/3101
#           roles:
#             - detect
#             - rtmp
#   camera2:
#     ffmpeg:
#       hwaccel_args: preset-nvidia-h264
#       inputs:
#         - path: rtsp://admin:0938447416hd@222.253.40.180:1024/Streaming/Unicast/channels/101
#           roles:
#             - detect
#             - rtmp
#   # camera1: # <------ Name the camera
#   #   ffmpeg:
#   #     hwaccel_args: preset-nvidia-h264
#   #     inputs:
#   #       - path: rtsp://admin:HQ-0907979696@anphukp5c.vncctv.com:1024/Streaming/Unicast/channels/101
#   #         roles:
#   #           - detect
#   #           - rtmp
#   # camera2:
#   #   ffmpeg:
#   #     hwaccel_args: preset-nvidia-h264
#   #     inputs:
#   #       - path: rtsp://admin:HQ-0907979696@anphukp5c.vncctv.com:1024/Streaming/Unicast/channels/201
#   #         roles:
#   #           - detect
#   #           - rtmp
#   #   detect:
#   #     height: 1080
#   #     width: 1920
#   #     fps: 5


cameras:
 camera1: # <------ Name the camera
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5c.vncctv.com:1024/Streaming/Unicast/channels/101
         roles:
           - detect
           - rtmp
 camera2:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5c.vncctv.com:1024/Streaming/Unicast/channels/201
         roles:
           - detect
           - rtmp
 camera3:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5c.vncctv.com:1024/Streaming/Unicast/channels/401
         roles:
           - detect
           - rtmp
 camera4:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5c.vncctv.com:1024/Streaming/Unicast/channels/501
         roles:
           - detect
           - rtmp
 camera5:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5.vncctv.com:1026/Streaming/Unicast/channels/1201
         roles:
           - detect
           - rtmp
 camera6:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5.vncctv.com:1026/Streaming/Unicast/channels/301
         roles:
           - detect
           - rtmp
 camera7:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5.vncctv.com:1026/Streaming/Unicast/channels/501
         roles:
           - detect
           - rtmp
 camera8:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://admin:HQ-0907979696@anphukp5.vncctv.com:1030/Streaming/Unicast/channels/1001
         roles:
           - detect
           - rtmp
 camera9:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/2401
         roles:
           - detect
           - rtmp
 camera10:
   ffmpeg:
     hwaccel_args: preset-nvidia-h264
     inputs:
       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/201
         roles:
           - detect
           - rtmp


 # camera12:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/2201
 #         roles:
 #           - detect
 #           - rtmp


 # camera13:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/2001
 #         roles:
 #           - detect
 #           - rtmp


 # camera14:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/1001
 #         roles:
 #           - detect
 #           - rtmp


 # camera15:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/601
 #         roles:
 #           - detect
 #           - rtmp


 # camera16:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/1301
 #         roles:
 #           - detect
 #           - rtmp


 # camera17:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/1201
 #         roles:
 #           - detect
 #           - rtmp


 # camera18:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/1601
 #         roles:
 #           - detect
 #           - rtmp


 # camera19:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/2401
 #         roles:
 #           - detect
 #           - rtmp
 # camera20:
 #   ffmpeg:
 #     hwaccel_args: preset-nvidia-h264
 #     inputs:
 #       - path: rtsp://kp4:hq-123456@anphukp4.vncctv.com:1026/Streaming/Unicast/channels/901
 #         roles:
 #           - detect
 #           - rtmp


detectors:
 tensorrt:
   type: tensorrt
   device: 0 #This is the default, select the first GPU


model:
 path: /trt-models/yolov7-tiny-416.trt
 input_tensor: nchw
 input_pixel_format: rgb
 width: 416
 height: 416


snapshots: # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
 enabled: True
 # Optional: save a clean PNG copy of the snapshot image (default: shown below)
 clean_copy: True
 # Optional: print a timestamp on the snapshots (default: shown below)
 timestamp: True
 # Optional: draw bounding box on the snapshots (default: shown below)
 bounding_box: True
 # Optional: crop the snapshot (default: shown below)
 crop: True
 # Optional: height to resize the snapshot to (default: original size)
 height: 175
 # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
 required_zones: []


record:
 enabled: True
 events:
   retain:
     default: 10
logger:
 # Optional: default log level (default: shown below)
 default: info
 # Optional: module by module log level configuration
 logs:
   frigate.mqtt: error


live:
 # Optional: Set the name of the stream that should be used for live view
 # in frigate WebUI. (default: name of camera)
 stream_name: camera_name
 # Optional: Set the height of the jsmpeg stream. (default: 720)
 # This must be less than or equal to the height of the detect stream. Lower resolutions
 # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
 height: 720
 # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
 # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
 quality: 8


# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
 # Optional: Position of the timestamp (default: shown below)
 #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
 position: "tl"
 # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
 #           Additional Examples:
 #             german: "%d.%m.%Y %H:%M:%S"
 format: "%m/%d/%Y %H:%M:%S"
 # Optional: Color of font
 color:
   # All Required when color is specified (default: shown below)
   red: 255
   green: 255
   blue: 255
 # Optional: Line thickness of font (default: shown below)
 thickness: 2
 # Optional: Effect of lettering (default: shown below)
 #           None (No effect),
 #           "solid" (solid background in inverse color of font)
 #           "shadow" (shadow for font)
 effect: shadow

