# syntax=docker/dockerfile:1.4

# https://askubuntu.com/questions/972516/debian-frontend-environment-variable
ARG DEBIAN_FRONTEND=noninteractive

# Make this a separate target so it can be built/cached optionally
FROM wheels as trt-wheels
ARG DEBIAN_FRONTEND
ARG TARGETARCH

# Add TensorRT wheels to another folder
COPY docker/tensorrt/requirements-amd64.txt /requirements-tensorrt.txt
RUN mkdir -p /trt-wheels && pip3 wheel --wheel-dir=/trt-wheels -r /requirements-tensorrt.txt

FROM tensorrt-base AS frigate-tensorrt
ENV TRT_VER=8.5.3
RUN --mount=type=bind,from=trt-wheels,source=/trt-wheels,target=/deps/trt-wheels \
    pip3 install -U /deps/trt-wheels/*.whl && \
    ldconfig
RUN pip3 install tensorflow-gpu==2.11.0
RUN pip3 install torch==2.1.0
RUN pip3 install torchvision==0.16.0
RUN ln -s /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer_plugin.so.8 /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer_plugin.so.7
RUN ln -s /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer.so.8 /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer.so.7
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.9/dist-packages/tensorrt
RUN ln -s /usr/local/lib/python3.9/dist-packages/nvidia/cufft/lib/libcufft.so.11 /usr/local/lib/python3.9/dist-packages/nvidia/cufft/lib/libcufft.so.10
RUN ln -s /usr/local/lib/python3.9/dist-packages/nvidia/cusparse/lib/libcusparse.so.12 /usr/local/lib/python3.9/dist-packages/nvidia/cusparse/lib/libcusparse.so.11
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.9/dist-packages/nvidia/cufft/lib:/usr/local/lib/python3.9/dist-packages/nvidia/cusparse/lib:/usr/local/lib/python3.9/dist-packages/nvidia/curand/lib:/usr/local/lib/python3.9/dist-packages/nvidia/cusolver/lib

WORKDIR /opt/frigate/
COPY --from=rootfs / /

# Dev Container w/ TRT
FROM devcontainer AS devcontainer-trt

COPY --from=trt-deps /usr/local/lib/libyolo_layer.so /usr/local/lib/libyolo_layer.so
COPY --from=trt-deps /usr/local/src/tensorrt_demos /usr/local/src/tensorrt_demos
COPY docker/tensorrt/detector/rootfs/ /
COPY --from=trt-deps /usr/local/lib/libyolo_layer.so /usr/local/lib/libyolo_layer.so
RUN --mount=type=bind,from=trt-wheels,source=/trt-wheels,target=/deps/trt-wheels \
    pip3 install -U /deps/trt-wheels/*.whl
RUN pip3 install tensorflow-gpu==2.11.0
RUN pip3 install torch==2.1.0
RUN pip3 install torchvision==0.16.0
RUN ln -s /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer_plugin.so.8 /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer_plugin.so.7
RUN ln -s /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer.so.8 /usr/local/lib/python3.9/dist-packages/tensorrt/libnvinfer.so.7
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.9/dist-packages/tensorrt
RUN ln -s /usr/local/lib/python3.9/dist-packages/nvidia/cufft/lib/libcufft.so.11 /usr/local/lib/python3.9/dist-packages/nvidia/cufft/lib/libcufft.so.10
RUN ln -s /usr/local/lib/python3.9/dist-packages/nvidia/cusparse/lib/libcusparse.so.12 /usr/local/lib/python3.9/dist-packages/nvidia/cusparse/lib/libcusparse.so.11
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.9/dist-packages/nvidia/cufft/lib:/usr/local/lib/python3.9/dist-packages/nvidia/cusparse/lib:/usr/local/lib/python3.9/dist-packages/nvidia/curand/lib:/usr/local/lib/python3.9/dist-packages/nvidia/cusolver/lib